### ISSUE TITLE
Radius is smaller then it should be

### ISSUE THREAD

**Issue by toffi3** [MattCzyr/ExplorersCompass#11]
![1](https://user-images.githubusercontent.com/84127414/149962962-77e493f6-221c-4787-b521-75b7aaee994a.png)
![2](https://user-images.githubusercontent.com/84127414/149962968-13894530-1b88-4230-a079-041f1ed15886.png)

**Comment by toffi3** [comment]
Mod Version 1.1.2 1.18.1
Forge Version 39.0.10

**Comment by MattCzyr** [comment]
This is happening because `maxSamples` is being reached before `maxRadius` is. In other words, no more samples can be taken, so the search stops even though the maximum radius has not yet been reached.

I'll look into raising the maximum configurable value for `maxSamples` in the next update so it's possible to get closer to the maximum searchable radius.
