### ISSUE TITLE
Compass takes very long to find certain structures

### ISSUE THREAD

**Issue by Torben8** [MattCzyr/ExplorersCompass#28]
Mod version: Fabric 1.19 2.1.1

I have multiple mods that add new structures to the world and the compass seems to not be able to find most of them but some of them are found.
When testing without any other mods i also noticed that it takes a really long time for the compass to find the nearest ocean monument because the search radius is increased very slowly.
If you need more information and mods i used i can provide that.

**Comment by MattCzyr** [comment]
Copy/pasting from #31:

This is due to the nature of the task. With biomes it's a bit simpler, since biomes span over many chunks, you can skip some and still have an accurate result, so it doesn't take too long. With structures, you need to check every single chunk to see if the structure is present or not, so it takes quite a while. I'm working on some potential shortcuts which could speed this up.

**Comment by YaogouYuki** [comment]
> Copy/pasting from #31:
> 
> This is due to the nature of the task. With biomes it's a bit simpler, since biomes span over many chunks, you can skip some and still have an accurate result, so it doesn't take too long. With structures, you need to check every single chunk to see if the structure is present or not, so it takes quite a while. I'm working on some potential shortcuts which could speed this up.

Can't I use the locate command?

**Comment by YaogouYuki** [comment]
Can't this mod use the locate command?

**Comment by MattCzyr** [comment]
Should be fixed in 1.3.0-forge and 2.2.0-fabric. The structure search has been significantly optimized as of these versions.
