### ISSUE TITLE
Multiple Compass Issues

### ISSUE THREAD

**Issue by tazzy989** [MattCzyr/ExplorersCompass#32]
I'm on Forge 1.18.2 using the "Better Minecraft Plus" modpack with a couple dozen other mods added, so it is a _very_ large modpack. 

Most structures the compass takes a *very* long time to search for. However, I also noticed it sometimes doesn't find structures that are there. I searched for a nether fortress and was told none were found within a 5k radius. However, upon exploring a bit, I found one about 500m to the west of our portal.

I also think the compass _desperately_ needs a clickable scroll bar to be able to scroll through the immense list of structures faster, as well as a "group by mod" option (if that's already implemented I apologize, I'm not currently looking at it). If I don't know the name of the structure I'm looking for, it is impossible to find in the structure list because it's simply so long. It would be much more convenient to be able to group by mod, then click to scroll down to the mod's section to browse what's added from that mod.

Thanks for your time and wonderful mods! Love both the compasses.

**Comment by MattCzyr** [comment]
It takes a while to find a structure just based on the nature of the task, since you need to check every single chunk to see if the structure is present or not. With biomes it's a bit simpler, since biomes span many chunks you don't need to check every single chunk, but with structures it's quite a time-consuming process. I'm looking into potential shortcuts to speed this up.

Regarding the compass not finding some nearby structures, this issue was discovered somewhat recently, in which some chunks were accidentally skipped, and so some structures could be missed. It was fixed in version 1.2.4 for 1.19.x, but I did not fix it in 1.18.x since it is no longer the latest major version. If there's enough interest I could.

If you want to group structures in the list by mod that adds them, you can click the "Sort By" button to "Sort By: Source", which will group structures by the source mod.

**Comment by tazzy989** [comment]
I'm noticing the issue almost every single time I use the compasses, either of them. I can very rarely find structures or biomes, it either "times out" after checking around 2000 blocks, or tells me none are found within 9000 blocks. The sort by function works, however there are _so_ many structures in the pack, it really needs a scroll bar so that we can click and drag down the list, it's impossible to scroll fast enough to ever see any of the structures at the bottom of the list.

**Comment by MattCzyr** [comment]
The slow searching should be fixed as of 1.3.0-forge and 2.2.0-fabric. The structure search has been significantly optimized in these versions. Also added a scroll bar.
